Fix blank fail comments again (#48)
* Try echoing output length?

* Try something else?

* One more thing?

* Order matters

* Syntax

* Disable bash -e

* Another run

* More bash magic

* More bash magic

* More bash magic, now magicaler

* Fix broken magic

* Working magic!  Add comments.

* Fix single workspace version

diff --git a/single-workspace-infra/terraform-plan/action.yaml b/single-workspace-infra/terraform-plan/action.yaml
--- a/single-workspace-infra/terraform-plan/action.yaml
+++ b/single-workspace-infra/terraform-plan/action.yaml
@@ -107,11 +107,27 @@ runs:
         commenter_exitcode: ${{ steps.validate.outputs.exitcode }}
     - name: TF Plan - Run
       id: plan
+      # have to use /bin/bash because GHA runs by default with `set -e` to end execution on any error.
+      # we want to capture the error instead.
+      shell: '/bin/bash {0}'
       run: |
-        OUTPUT=$(terraform plan -lock=false -input=false -out=tfplan 2>&1 | tee /dev/fd/2; exit ${PIPESTATUS[0]})
-        echo "::set-output name=plan-output::${OUTPUT::65000}"
-        echo "::set-output name=exitcode::$?"
-      shell: bash
+        # a lot going on here.  copy the stdout file handle to fd5.
+        exec 5>&1
+
+        # merge stderr into stdout and print it to fd5 (parent shell's stdout); exit with the code from terraform plan
+        OUTPUT=$(terraform plan -lock=false -input=false -out=tfplan 2>&1 | tee /dev/fd/5; exit ${PIPESTATUS[0]})
+
+        # store the exit code here
+        EXITCODE=$?
+
+        # github actions doesn't allow us to set a multiline output so we cat it to the environment
+        echo "PLAN_OUTPUT<<EOF" >> $GITHUB_ENV
+        echo "${OUTPUT::65000}" >> $GITHUB_ENV
+        echo "EOF" >> $GITHUB_ENV
+
+        # set exit code for pickup later, and make sure we exit with same code
+        echo "::set-output name=exit::${EXITCODE}"
+        exit $EXITCODE
     - name: Post TF Plan Comment
       if: ${{ always() && github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && inputs.enable_plan_commenter == 'true' }}
       uses: GetTerminus/terraform-pr-commenter@master
@@ -121,7 +137,7 @@ runs:
         TF_WORKSPACE: ${{ inputs.tf_workspace }}
       with:
         commenter_type: plan
-        commenter_input: ${{ steps.plan.outputs.plan-output }}
+        commenter_input: ${{ env.PLAN_OUTPUT }}
         commenter_plan_path: tfplan
-        commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
+        commenter_exitcode: ${{ steps.plan.outputs.exit }}
         terraform_version: ${{ inputs.terraform_version }}
