fix: fix dd metaupload (#9)
* fix: metaupload test

* fix: metaupload test

* fix: metaupload test

* fix: metaupload test

* fix: metaupload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

* fix: git metadata upload

diff --git a/multi-workspace-infra/terraform-plan/action.yaml b/multi-workspace-infra/terraform-plan/action.yaml
--- a/multi-workspace-infra/terraform-plan/action.yaml
+++ b/multi-workspace-infra/terraform-plan/action.yaml
@@ -21,6 +21,7 @@ inputs:
                   removed after.'
     required: false
     default: 'false'
+    
 runs:
   using: "composite"
   steps:
@@ -36,7 +37,8 @@ runs:
         terraform_version: ${{ inputs.terraform_version }}
     - name: Terraform Format Check
       id: fmt
-      run: terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
+      run: |
+        terraform fmt -check -recursive || echo "::set-output name=exitcode_continue_on_error::$?" 
       #TODO: Uncomment once github supports it
       #continue-on-error: true
       shell: bash
